### ISSUE TITLE
style: wrong initialization order

### ISSUE THREAD

**Issue by maddin200** [Thomas-Mielke-Software/ECTImport#2]
ECTImport-master/ResizableLayout.h line 99 / line 121:

	hWnd(hwnd), nCallbackID(0), bMsgSupport(FALSE), // <- should be below
		anchorTopLeft(tl_type), marginTopLeft(tl_margin),
		anchorBottomRight(br_type), marginBottomRight(br_margin)

**Comment by thomiel** [comment]
Was meinst Du damit?

Das ist ja nun eine Headerdatei einer externen Bibliothek. Ich verstehe Deine Motivation für diese einzelnen Hinweise nicht. Im Code gibt es sicher noch massenweise Refactoringpotenzial.

**Comment by maddin200** [comment]
Die Reihenfolge der Initialisierung ist unterschiedlich wie die Reihenfolge der Deklarationen, aber kann natürlich "won't change" sein.

**Comment by thomiel** [comment]
Hier bringt das eher wenig. Beim nächsten Updaten der Lib ist das wieder überschrieben.

Der richtige Ort, das anzubringen, wäre beim Autor hier: https://github.com/ppescher/resizablelib

Ich frage mich nur, ob Deine anscheinend automatisch generierten Issues irgendein bestimmtes Ziel verfolgen. Die Hinweise machen den Code im Ganzen ja nicht wirklich besser. Auf mich wirkt es, als würdest Du ein privates Forschungsprojekt auf GitHub verfolgen.

Wenn Du hier wirklich was verbessern willst, forke doch einfach das Repo, lass Deinen Code-Nazi drüberlaufen und schicke einen pull request mit der korrigierten Version. Das wäre effizenter als diese zusammenhanglosen punktuellen Codeanalyse-Nadelstiche. ;)

**Comment by thomiel** [comment]
Ahh, jetzt verstehe ich. Du bist auf gitcoin! Gibt es Kryptogeld dafür, dass Du bei GitHub Issues öffnest?

**Comment by maddin200** [comment]
leider falsch - benutze Easy Cash und entwickle Open Source.

**Comment by thomiel** [comment]
Lust etwas zum Code beizutragen, das über Codeanalyse-Schnipsel hinausgeht?

**Comment by maddin200** [comment]
Schaue mal was passt.

Codeanalyse sollte nur natürlich wirkliche Issues anmarkern, aber meiner Erfahrung ist es besser wenn die Korrektur ein Contributor vornimmt - 4 Augen sehen mehr.

**Comment by thomiel** [comment]
Z.b. wäre es ziemlich cool, wenn das Import-Plugin eine Checkbox zur Auswahl der zu importierenden Buchungen hätte und das nicht über Selektieren der einzelnen Zeilen liefe, was ein bisschen volatil ist. Stattdessen könnte man ein Kontextmenü haben mit "Selektierte für Import auswählen", "Auswahl aufheben", "alle auswählen", "Auswahl aller aufheben" oder so.

**Comment by maddin200** [comment]
Das ist ein fork:
https://github.com/maddin200/ECTImport
für playing around und minor changes

**Comment by thomiel** [comment]
inaktivität
